//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.22 at 11:24:35 PM NOVT 
//


package analizetextpackage.xmlmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ModelType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModelType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rules" type="{}RulesType"/>
 *         &lt;element name="approvedFacts" type="{}ApprovedFactsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelType", propOrder = {
    "rules",
    "approvedFacts"
})
public class ModelType {

    @XmlElement(required = true)
    protected RulesType rules;
    @XmlElement(required = true)
    protected ApprovedFactsType approvedFacts;

    /**
     * Gets the value of the rules property.
     * 
     * @return
     *     possible object is
     *     {@link RulesType }
     *     
     */
    public RulesType getRules() {
        return rules;
    }

    /**
     * Sets the value of the rules property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulesType }
     *     
     */
    public void setRules(RulesType value) {
        this.rules = value;
    }

    /**
     * Gets the value of the approvedFacts property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovedFactsType }
     *     
     */
    public ApprovedFactsType getApprovedFacts() {
        return approvedFacts;
    }

    /**
     * Sets the value of the approvedFacts property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovedFactsType }
     *     
     */
    public void setApprovedFacts(ApprovedFactsType value) {
        this.approvedFacts = value;
    }

}
