//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.22 at 11:24:35 PM NOVT 
//


package analizetextpackage.xmlmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RuleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="factExpression" type="{}factExpressionType"/>
 *           &lt;element name="andExpression" type="{}andExpressionType"/>
 *           &lt;element name="orExpression" type="{}orExpressionType"/>
 *         &lt;/choice>
 *         &lt;element name="resultingFact" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RuleType", propOrder = {
    "factExpression",
    "andExpression",
    "orExpression",
    "resultingFact"
})
public class RuleType {

    protected String factExpression;
    protected AndExpressionType andExpression;
    protected OrExpressionType orExpression;
    @XmlElement(required = true)
    protected String resultingFact;

    /**
     * Gets the value of the factExpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFactExpression() {
        return factExpression;
    }

    /**
     * Sets the value of the factExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFactExpression(String value) {
        this.factExpression = value;
    }

    /**
     * Gets the value of the andExpression property.
     * 
     * @return
     *     possible object is
     *     {@link AndExpressionType }
     *     
     */
    public AndExpressionType getAndExpression() {
        return andExpression;
    }

    /**
     * Sets the value of the andExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link AndExpressionType }
     *     
     */
    public void setAndExpression(AndExpressionType value) {
        this.andExpression = value;
    }

    /**
     * Gets the value of the orExpression property.
     * 
     * @return
     *     possible object is
     *     {@link OrExpressionType }
     *     
     */
    public OrExpressionType getOrExpression() {
        return orExpression;
    }

    /**
     * Sets the value of the orExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrExpressionType }
     *     
     */
    public void setOrExpression(OrExpressionType value) {
        this.orExpression = value;
    }

    /**
     * Gets the value of the resultingFact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResultingFact() {
        return resultingFact;
    }

    /**
     * Sets the value of the resultingFact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResultingFact(String value) {
        this.resultingFact = value;
    }

}
